spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: mGy6GAzdawFPTJ7R
    hikari:
      maximum-pool-size: 20
  application:
    name: mysql-ddl-test
server:
  servlet:
    context-path: /mysql-ddl-test
